# Generated by Django 6.0.6 on 2026-08-22 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='printingorder',
            name='calculated_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='printingorder',
            name='copies',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='printingorder',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='printingorder',
            name='final_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='printingorder',
            name='print_type',
            field=models.CharField(choices=[('bw', 'Black & White'), ('color', 'Color')], default='bw', max_length=10),
        ),
        migrations.AddField(
            model_name='printingorder',
            name='side',
            field=models.CharField(choices=[('single', 'Single Side'), ('double', 'Double Side')], default='single', max_length=10),
        ),
        migrations.AddField(
            model_name='printingorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='printingorder',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='PrintingFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='printing/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='printing.printingorder')),
            ],
        ),
    ]
